on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

name: CI

jobs:

  jsonlint:
    name: Lint JSON
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y python3-demjson
      - uses: actions/checkout@v5
      - run: jsonlint --strict directory.json

  sort:
    name: Sort JSON
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install -y diffutils jq
      - uses: actions/checkout@v5
      - run: diff --color -u3 directory.json <(cat directory.json | jq -S) -L directory.json -L directory.json
