---
on:
    push:
        paths:
          - directory.json
    pull_request:
        branches:
          - master
        paths:
          - directory.json
    workflow_dispatch:

jobs:
    jsonlint:
        name: Lint JSON
        runs-on: ubuntu-latest
        steps:
        - run: sudo apt-get install -y python3-demjson
        - uses: actions/checkout@v2
        - run: jsonlint --strict ./directory.json
    check-url:
        name: Check URL
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: technote-space/get-diff-action@v6
          with:
            GET_FILE_DIFF: true
        - run: |  
            echo ${{ env.DIFF }}
