---
on:
    push:
        paths:
          - directory.json
    pull_request:
        branches:
          - master
        paths:
          - directory.json
    workflow_dispatch:

jobs:
    jsonlint:
        name: Lint JSON
        runs-on: ubuntu-latest
        steps:
        - run: sudo apt-get install -y python3-demjson
        - uses: actions/checkout@v2
        - run: jsonlint --strict ./directory.json
    check-url:
        name: Check URL
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
          - name: Get changed files
            id: changes
            # Set outputs using the command.
            run: |
              echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
